### PR TITLE
[WIP] rough outline for net functions

### PR DESCRIPTION
**Pull request by brandonros**
Part of https://github.com/horhof/quickjs/issues/1

### CODE REVIEW

**Comment by kevinkassimo** [comment]
I don't think this is an official repo by Bellard. Maybe you (or we, I am also a bit interested in the project) should email him and see if it is possible that it could be hosted on Github (of which I doubt he would ever do that) or at least provide an open channel for sending patches?

Also the original source code does not seems to be even using Git.

**Comment by danielsss** [comment]
@kevinkassimo Obviously, This is not an official repo.

**Comment by brandonros** [comment]
What do you guys think the best way to expose TCP/IP sockets to the runtime are? Meaning... green threads? epoll? select?

**Comment by brandonros** [comment]
```javascript
const stringToArrayBuffer = (input) => {
  const buffer = new ArrayBuffer()
  for (let i = 0; i < input.length; ++i) {
    buffer[i] = input.charCodeAt(i)
  }
  return buffer
}
const socket = net.socket(net.AF_INET, net.SOCK_STREAM, 0);
const ip = 0xACD90FCE // dig google.com = 172.217.15.206 = 0xACD90FCE
const port = 80
if (net.connect(socket, ip, port) !== 0) {
  throw new Error('Connect failed')
}
const request = "GET / HTTP 1.1\r\n\r\n"
if (net.send(socket, stringToArrayBuffer(request), request.length, 0) !== 18) {
  throw new Error('send failed')
}
const buf = new ArrayBuffer(4096)
for (let i = 0; i < 4096; ++i) {
  buf[i] = 0
}
if (net.recv(socket, buf, 4096, 0) <= 0) {
  throw new Error('recv failed')
}
```

code i've been trying to get working

**Comment by horhof** [comment]
https://www.freelists.org/list/quickjs-devel

**Comment by Sxs7513** [comment]
> I don't think this is an official repo by Bellard. Maybe you (or we, I am also a bit interested in the project) should email him and see if it is possible that it could be hosted on Github (of which I doubt he would ever do that) or at least provide an open channel for sending patches (plus some mailing list)?
> 
> Also the original source code does not seems to be even using Git.

can u tell me his email?

**Pull request closed without merging**
